name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 (北京时间早上8点) 自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: hydy100
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: main
          base: main
